language: python
python:
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y redis-server
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: ./tests.py